/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

var serviceUrl = 'http://pauker.at/pauker_xml.php?langt=';
var xmlHttpRequest;

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    dashcode.setupParts();
    fillLanguageList();
    initializeXMLHttpRequest();
    
    document.getElementById('search').focus();
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
    focusInput();
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront");
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

if (window.widget)
{
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}


function visitWebsite(event)
{
    widget.openURL("http://www.nullsinn.net/widgets");
}

function fillLanguageList() {
    var searchlanguage = widget.preferenceForKey("searchlanguage");
    var languageList = document.getElementById('activeLanguagePopup');
    var selectedIndex = 0;
    var index = 0;
    for (var langCode in availableLanguages) {
        var langName = availableLanguages[langCode];
        if(langCode == searchlanguage) {
            selectedIndex = index;
        }
        addOption(languageList.object.select, langName, langCode);
        index++;
    }
    languageList.object.setSelectedIndex(selectedIndex);
    
}

function addOption(selectbox,text,value ) {
	var optn = document.createElement("option");
	optn.text = text;
	optn.value = value;
	selectbox.options.add(optn); // 10.4 doesn't unterstand this
}



function changeLanguage(event)
{
    // Save selectedLanguage as default
    var languageList = document.getElementById('activeLanguagePopup');
    var searchlanguage = languageList.object.getValue();
    widget.setPreferenceForKey(searchlanguage, "searchlanguage");
}

function toggleLoader(showloader) {
	if(showloader) {
		document.getElementById("spinningimg").style.display = "block";
	} else {
		document.getElementById("spinningimg").style.display = "none";
	}
}

function doSearchIF(event) {
	if(event.keyCode == 13) { // Start search on "enter"
		doSearch(event);
	}
}

function doSearch(event)
{
    var searchString = document.getElementById('search').value.trim();
    doSearchInternal(searchString);
}

function doSearch2(searchString) {
    if(searchString == null || searchString.trim() == "") {
		return;
	}
    document.getElementById('search').value = searchString.trim();
    doSearchInternal(searchString);
    focusInput();
}

function doSearchInternal(searchString)
{
    var searchLanguage = document.getElementById('activeLanguagePopup').object.getValue();
    if(searchString == null || searchString.trim() == "") {
		return;
	}
    searchString = escapeXML(searchString);
    
    // display loading animation
	toggleLoader(true);
    
    var url = serviceUrl+searchLanguage;
    xmlHttpRequest.open("POST", url);
	xmlHttpRequest.setRequestHeader("Cache-Control", "no-cache");
	xmlHttpRequest.send('<such>'+searchString+'</such>');
    
}

function parseResponseXML(xmlRequest) {
    var rs = xmlRequest.responseXML;
	if(rs != null) {
		var rslist = rs.getElementsByTagName("line"); 
		if(rslist.length > 0) {
			var table = document.createElement("table");
			for(i=0;i<rslist.length; i++) {
				var rline = rslist[i];
				var q = rline.getAttribute('q');
				var a = rline.getAttribute('a');
				
				// create row
				var trow = document.createElement("tr");
				trow.setAttribute("class", (i%2==0?"even":"odd"));
				
				// create key column
				var tdatakey = document.createElement("td");
				tdatakey.innerHTML = tdNode(q);
				trow.appendChild(tdatakey);
				
				// create value column
				var tdatavalue = document.createElement("td");
				tdatavalue.innerHTML = tdNode(a);
				trow.appendChild(tdatavalue);
				
				// append row to table
				table.appendChild(trow);
			}
			setContent(table);
		} else {
			setContent(document.createTextNode(getLocalizedString("Found nothing.")));
		}
	} else {
		setContent(document.createTextNode(getLocalizedString("Found nothing.")));
	}
	
	// hide loading animation
	toggleLoader(false);
}

function escapeXML(s) {
	if(s == null) return s;
	s = s.replace(/&/g,"&amp;");
	s = s.replace(/</g,"&lt;");
	s = s.replace(/>/g,"&gt;");
	return s;
}

function tdNode(nt) {
	var newstring = nt.replace(/([\wßüäöÜÄÖåÅøØóÓáÁúÚ]{3,})/g,"<span class=\"link\" onclick=\"doSearch2('$1')\">$1</span>");
	return newstring;
}

function setContent(domelem) {
    var scrollbox = document.getElementById("scrollArea").object;
	if ( scrollbox.content.hasChildNodes() ){
		while ( scrollbox.content.childNodes.length >= 1 ){
			scrollbox.content.removeChild( scrollbox.content.firstChild );       
		} 
	}
	scrollbox.content.appendChild(domelem);
	scrollbox.refresh();
}

function initializeXMLHttpRequest() {
    xmlHttpRequest = new XMLHttpRequest();
    var onloadHandler = function() { 
		parseResponseXML(xmlHttpRequest);
	};
    var onerrorHandler = function() { 
		setContent(document.createTextNode(getLocalizedString("Found nothing.")));
	};

    xmlHttpRequest.onload = onloadHandler;
    xmlHttpRequest.onerror = onerrorHandler;
}

function focusInput() {
    document.getElementById('search').focus();
    document.getElementById('search').select();
}
